version: "3.9"
services:
  core:
    build:
      context: ../../apps/core
      dockerfile: Dockerfile
    container_name: core-dev
    env_file:
      - ../../config/env/dev-local/.env
    networks:
      - dev-network
    ports:
      - "4000:4000"
    volumes:
      - ../../apps/core:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  app:
    build:
      context: ../../apps/app
      dockerfile: Dockerfile
    container_name: app-dev
    networks:
      - dev-network
    ports:
      - "5173:5173"
    volumes:
      - ../../apps/app:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000
    command: npm run dev

  nginx:
    build:
      context: ../../apps/nginx
      dockerfile: Dockerfile
    container_name: nginx-dev
    networks:
      - dev-network
    ports:
      - "80:80"
    volumes:
      - ../../apps/nginx:/etc/nginx/conf.d
    depends_on:
      - app
      - core

networks:
  dev-network:
    driver: bridge
